# Site settings
title: ossia | Open Software System for Interactive Applications
email: contact@ossia.io
description: > # this means to ignore newlines until "baseurl:"
  Open Software System for Interactive Applications - home of ossia score, a free, open-source, cross-platform intermedia sequencer for precise and flexible scripting of interactive scenarios.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ossia.io" # the base hostname & protocol for your site
image: "/assets/score-logo.png"
include: ["_pages", "CNAME", ".nojekyll", "score-last-version.txt", "download-stats.json"]
# exclude: ["vendor"]
permalink: /posts/:title/
score_version: 3.1.11
score_released_date: "June 23, 2023"
plugins:
  - jekyll-sitemap
  - jekyll-assets

# Build settings
markdown: kramdown
collections:
  score_features:
    output: false
  libossia_features:
    output: true

assets:
  sources:
    - assets
    - images
    - css
    - js
  compress:
    css: true
    js: uglifier
